export const INITIALIZE_QUIZ = 'INITIALIZE_QUIZ';
export const INCREMENT_QUESTION = 'INCREMENT_QUESTION';
export const CALCULATE_SCORE = 'CALCULATE_SCORE';
export const CHOOSE_OPTION = 'CHOOSE_OPTION';
export const RESET_QUIZ = 'RESET_QUIZ';